-- Open Brain local index: SQLite schema.
--
-- The markdown files in the vault stay canonical. This database is a
-- rebuildable index built FROM those files, so it can always be deleted and
-- regenerated by running `python brainctl.py index`. Nothing here is a source
-- of truth; the .md notes are.
--
-- The full-text-search table (notes_fts) is created in code, not here, because
-- it depends on the FTS5 module being compiled into SQLite. The indexer detects
-- that at runtime and falls back to a plain LIKE search if FTS5 is missing, so
-- this file only holds the base tables that always work.

PRAGMA journal_mode = WAL;
PRAGMA foreign_keys = ON;

-- One row per markdown note. `embedding` is reserved for the backend-later step
-- (semantic search); it stays NULL until `python brainctl.py embed` fills it.
CREATE TABLE IF NOT EXISTS notes (
  id              INTEGER PRIMARY KEY,
  slug            TEXT UNIQUE NOT NULL,   -- stable identity: frontmatter `name`, else filename stem
  path            TEXT UNIQUE NOT NULL,   -- vault-relative path, forward slashes
  folder          TEXT,                   -- top-level folder (Claude Memory, Sessions, Ventures, ...)
  title           TEXT,                   -- display title (frontmatter title/name, else stem)
  description     TEXT,                   -- one-line recall hook from frontmatter
  type            TEXT,                   -- user|feedback|project|reference|session|venture|note|...
  tags            TEXT,                   -- JSON array of tag strings
  body            TEXT,                   -- markdown body, frontmatter stripped
  frontmatter     TEXT,                   -- JSON of the full parsed frontmatter
  word_count      INTEGER,
  created         TEXT,                   -- ISO date: frontmatter date/created, else file ctime
  modified        TEXT,                   -- ISO date: file mtime
  content_hash    TEXT,                   -- sha256 of the raw file, to skip unchanged notes on reindex
  embedding       BLOB,                   -- reserved: packed float32 vector, filled later
  embedding_model TEXT                    -- which model produced `embedding`
);

CREATE INDEX IF NOT EXISTS idx_notes_type   ON notes(type);
CREATE INDEX IF NOT EXISTS idx_notes_folder ON notes(folder);

-- Tags, normalized one row per (note, tag), for clean filtering and counts.
CREATE TABLE IF NOT EXISTS note_tags (
  note_id INTEGER NOT NULL REFERENCES notes(id) ON DELETE CASCADE,
  tag     TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_note_tags_tag  ON note_tags(tag);
CREATE INDEX IF NOT EXISTS idx_note_tags_note ON note_tags(note_id);

-- The [[wikilink]] graph. `target_id` is NULL when the link points at a note
-- that does not exist yet, which the vault treats as a valid "worth writing"
-- marker, so a NULL here is a feature, not a broken row.
CREATE TABLE IF NOT EXISTS links (
  source_id   INTEGER NOT NULL REFERENCES notes(id) ON DELETE CASCADE,
  target_norm TEXT NOT NULL,   -- normalized link target (lowercased, alias/heading stripped)
  target_id   INTEGER,         -- resolved note id, NULL if unresolved
  raw         TEXT             -- the exact [[wikilink]] text as written
);

CREATE INDEX IF NOT EXISTS idx_links_source ON links(source_id);
CREATE INDEX IF NOT EXISTS idx_links_target ON links(target_norm);

-- Small key/value bag for index metadata (last indexed time, counts, fts flag).
CREATE TABLE IF NOT EXISTS meta (
  key   TEXT PRIMARY KEY,
  value TEXT
);
